Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using homeopatija.Data.Dtos;

namespace homeopatija.Controllers
{
    public class ShoppingCartController : Controller
    {
        private ShoppingCartViewModel GetCart()
        {
            var cart = new ShoppingCartViewModel
            {
                Items = new List<ShoppingCartItem>
                {
                    new ShoppingCartItem { ProductId = 1, ProductName = "Homeopatinė Arnica Montana", Price = 5.99m, Quantity = 1 },
                    new ShoppingCartItem { ProductId = 2, ProductName = "Homeopatinis Belladonna", Price = 7.49m, Quantity = 2 }
                }
            };

            return cart;
        }

        // GET: ShoppingCartController
        public ActionResult Index()
        {
            var cart = GetCart();
            return View(cart);
        }

        // GET: ShoppingCartController/Checkout
        public ActionResult Checkout()
        {
            return View();
        }

        // GET: ShoppingCartController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ShoppingCartController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ShoppingCartController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ShoppingCartController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ShoppingCartController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ShoppingCartController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ShoppingCartController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using homeopatija.Entities;
using homeopatija.Data.Dtos;
using homeopatija.Repos;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.WebUtilities;
using System.Text.Encodings.Web;
using System.Text;

namespace homeopatija.Controllers
{
    public class UserController : Controller
    {
        private readonly HomeopatijaContext db;

        public UserController(HomeopatijaContext db)
        {
            this.db = db;
        }

        public void ShowStatusMessage(string text)
        {
            TempData["StatusMessage"] = text;
        }

        [Route("Details")]
        public ActionResult Details(int id)
        {
            return View("Details");
        }

        [Route("Register")]
        public ActionResult Register()
        {
            return View("Register");
        }

        [Route("Login")]
        public ActionResult Login()
        {
            
            return View("Login");
        }

        [HttpPost("Register")]
        public ActionResult Create(RegisterUser userData)
        {
            /*
            if (userData.Password != userData.RepeatPassword)
            {
                ModelState.AddModelError("RepeatPassword", "Pakartotas slaptažodis nesutampa");
                return View("Register");
            }

            Console.WriteLine("foo");
            Console.WriteLine(userData.Password);
            bool success = UserRepo.Create(db, userData.Name, userData.Surname, userData.Password, userData.Email, userData.Phone, userData.Address);
            if (!success)
            {
                ShowStatusMessage("Nepavyko užsiregistruoti");
                return View("Register");
            }

            ShowStatusMessage("Sėkmingai užsiregistruota");
            return RedirectToAction("Login");
            */
            return RedirectToPage("/404");
        }



        // GET: UserController/Edit/5
        public ActionResult Edit(int id)
        {
            User user = new User(){
                Name = "Petras",
                Surname = "Dovydaitis",
                //Password = "grietinė69",
                Email = "petras.dovydaitis@vilkaviškiopieninė.lt",
                //Phone = "+370********"
            };

            return View("Edit", user);
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            return View();
            /*try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }*/
        }

        // GET: UserController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - homeopatija</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/homeopatija.styles.css" asp-append-version="true" />
  <link rel="icon" href="@Url.Content("~/favicon.png")" />
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
</head>

<body class="" x-data="{showNotification: @(TempData.ContainsKey("StatusMessage").ToString().ToLower()) }">
  @* <div id="notification" >Notification</div> *@

  <header>
    <nav
      class="navbar sticky navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
      <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">homeopatija</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Drug" asp-action="Index">Vaistai</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Disease" asp-action="Index">Ligos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Symptom" asp-action="Index">Simptomai</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Bureja" asp-action="Index">Bureja</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="FAQ" asp-action="Index">DUK</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index">Prekių
                krepšelis</a>
            </li>
            <li class="nav-item">
               <a class="nav-link text-dark" href="/Identity/Account/Login">Prisijungimas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="/Identity/Account/Register">Registracija</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Edit">Paskyros redagavimas</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

    
  @* <div class=""> *@
  <div class="container">
        @{
            Html.RenderPartial("/Views/Components/_Notification.cshtml");
        }
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-muted">
    <div class="container">
      ඞ 2023 - homeopatija - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privatumo politika</a>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>

</html>